window_name = "Editor"
resolution = (800, 600)
frames_per_second = 30
animation_frames_per_second = 6
background_color = (0, 0, 0)
lru_cache_landscapes_light_maxsize = 1024
lru_cache_triangles_maxsize = 8192
landscape_light_factor = 0.333
landscape_dark_factor = 0.5
terrain_light_factor = 0.75
camera_discretization_factor = 0
camera_max_move_distance = 100
timeout_duration = 0.1
transition_stretch_factor = 1/3
